package net.cakeyfox.common

object Placeholders {
    const val USER_GLOBAL_NAME = "{user}"
    const val USER_MENTION = "{@user}"
    const val USER_USERNAME = "{user.username}"
    const val USER_ID = "{user.id}"
    const val USER_AVATAR = "{user.avatar}"
    const val GUILD_NAME = "{guild.name}"
    const val GUILD_ID = "{guild.id}"
    const val GUILD_MEMBERS = "{guild.memberCount}"
    const val GUILD_ICON = "{guild.icon}"
    const val CHANNEL_NAME = "{channel.name}"
    const val CHANNEL_ID = "{channel.id}"
    const val VIDEO_URL = "{video.url}"
    const val MEMBER_NAME = "{member.name}"
    const val MEMBERS_ID = "{member.id}"
    const val MEMBER_MENTION = "{@member}"
    const val MEMBER_AVATAR = "{member.avatar}"
    const val STAFF_NAME = "{staff.name}"
    const val STAFF_ID = "{staff.id}"
    const val REASON = "{reason}"
    const val DURATION = "{duration}"
    const val STAFF_MENTION = "{@staff}"
    const val STAFF_AVATAR = "{staff.avatar}"
    const val PUNISHMENT_TYPE = "{punishment.type}"
}